### ISSUE TITLE
code of video input

### ISSUE THREAD

**Issue by ganeshmanikanta** [huma-teknofest/Keras-RetinaNet-for-Teknofest-2019#1]
hey,
Thank you so much for the work. I have a small question.
Do you have code for giving input as video and it can detect cars or pedestrians in it?
Thank you.

**Comment by Gazi13** [comment]
Maybe late for you but can help others 

https://github.com/priya-dwivedi/aerial_pedestrian_detection/blob/master/ResNet50RetinaNet-Video.ipynb

**Comment by ganeshmanikanta** [comment]
Thanks for the reply...found this one months before..anyways thanks for reply.. :)
